---
system_packages:
  - build-essential
  - git
  - curl
  - make
  - vim
  - unzip
  - nodejs 
  - graphicsmagick
  - libevent-dev
  - nginx
  - clang 
  - whois
  - python-setuptools
  - python-dateutil
  - python-software-properties 
  - python-gdal 
  - python-mapnik2 
  - python-pyproj
  - python-dev 
  - python-imaging
  - python-virtualenv
  - libpq-dev
  - libgdal1h
  - libgdal-dev
  - zlib1g-dev
  - libexpat1
  - libexpat1-dev
  - libxml2
  - libxml2-dev
  - libgeos-dev
  - libgeos++-dev
  - libprotobuf-dev
  - protobuf-compiler
  - libsparsehash-dev
  - libboost-dev
  - libgdal1-dev
  - libproj-dev
  - subversion
  - doxygen
  - graphviz
  - pgadmin3
  - libosmpbf-dev
  - osm2pgsql
  - tilemill 
  - libmapnik 
  - gdal-bin
  - mapnik-utils
  - openjdk-7-jdk 
  - libprotobuf-c0-dev
  - libfontconfig1:i386
  - libx11-6:i386 
  - libxrender1:i386 
  - libxext6:i386 
  - libgl1-mesa-glx:i386 
  - libglu1-mesa:i386 
  - libglib2.0-0:i386 
  - libsm6:i386
#  - postgresql-9.1
#  - postgresql-9.1-postgis-2.0
#  - postgresql-contrib-9.1
#  - proj 
#  - libprotobuf7

